language: node_js

os:
  - linux
  - osx

node_js: "12.4.0"

services:
  - xvfb

script:
  - npx nyc --reporter=lcov npm test && npx codecov

notifications:
  email:
    on_success: never

on_failure: change
