name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: Europe/Amsterdam
        timezoneMacos: Europe/Amsterdam
        timezoneWindows: W. Europe Standard Time
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.18.3'
    - run: npm install
    - run: npm test
      env:
        CI: true
